# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(613, 758)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 19, 0, 1, 1)
        self.diskImageBrowseBtn = QtGui.QPushButton(self.centralwidget)
        self.diskImageBrowseBtn.setObjectName(_fromUtf8("diskImageBrowseBtn"))
        self.gridLayout.addWidget(self.diskImageBrowseBtn, 6, 3, 1, 1)
        self.diskImageSource = QtGui.QLineEdit(self.centralwidget)
        self.diskImageSource.setText(_fromUtf8(""))
        self.diskImageSource.setObjectName(_fromUtf8("diskImageSource"))
        self.gridLayout.addWidget(self.diskImageSource, 6, 0, 1, 2)
        self.destination = QtGui.QLineEdit(self.centralwidget)
        self.destination.setText(_fromUtf8(""))
        self.destination.setObjectName(_fromUtf8("destination"))
        self.gridLayout.addWidget(self.destination, 10, 0, 1, 2)
        self.startScanBtn = QtGui.QPushButton(self.centralwidget)
        self.startScanBtn.setObjectName(_fromUtf8("startScanBtn"))
        self.gridLayout.addWidget(self.startScanBtn, 28, 0, 1, 1)
        self.directorySource = QtGui.QLineEdit(self.centralwidget)
        self.directorySource.setText(_fromUtf8(""))
        self.directorySource.setObjectName(_fromUtf8("directorySource"))
        self.gridLayout.addWidget(self.directorySource, 3, 0, 1, 2)
        self.textEdit_2 = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.gridLayout.addWidget(self.textEdit_2, 27, 0, 1, 2)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 25, 0, 1, 3)
        self.destinationBrowseBtn = QtGui.QPushButton(self.centralwidget)
        self.destinationBrowseBtn.setObjectName(_fromUtf8("destinationBrowseBtn"))
        self.gridLayout.addWidget(self.destinationBrowseBtn, 10, 3, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout.addWidget(self.radioButton_2, 5, 0, 1, 1)
        self.directoryBrowseBtn = QtGui.QPushButton(self.centralwidget)
        self.directoryBrowseBtn.setObjectName(_fromUtf8("directoryBrowseBtn"))
        self.gridLayout.addWidget(self.directoryBrowseBtn, 3, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 2)
        self.identifier = QtGui.QLineEdit(self.centralwidget)
        self.identifier.setText(_fromUtf8(""))
        self.identifier.setObjectName(_fromUtf8("identifier"))
        self.gridLayout.addWidget(self.identifier, 12, 0, 1, 2)
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout.addWidget(self.radioButton, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 9, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 13, 0, 1, 1)
        self.scanArchivesBtn = QtGui.QCheckBox(self.centralwidget)
        self.scanArchivesBtn.setChecked(True)
        self.scanArchivesBtn.setObjectName(_fromUtf8("scanArchivesBtn"))
        self.gridLayout.addWidget(self.scanArchivesBtn, 14, 1, 1, 1)
        self.removeFilesBtn = QtGui.QCheckBox(self.centralwidget)
        self.removeFilesBtn.setObjectName(_fromUtf8("removeFilesBtn"))
        self.gridLayout.addWidget(self.removeFilesBtn, 8, 0, 1, 2)
        self.btn_sha1 = QtGui.QRadioButton(self.centralwidget)
        self.btn_sha1.setObjectName(_fromUtf8("btn_sha1"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.btn_sha1)
        self.gridLayout.addWidget(self.btn_sha1, 21, 0, 1, 1)
        self.skipClamscanBtn = QtGui.QCheckBox(self.centralwidget)
        self.skipClamscanBtn.setObjectName(_fromUtf8("skipClamscanBtn"))
        self.gridLayout.addWidget(self.skipClamscanBtn, 14, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 11, 0, 1, 1)
        self.btn_md5 = QtGui.QRadioButton(self.centralwidget)
        self.btn_md5.setChecked(True)
        self.btn_md5.setObjectName(_fromUtf8("btn_md5"))
        self.buttonGroup.addButton(self.btn_md5)
        self.gridLayout.addWidget(self.btn_md5, 20, 0, 1, 1)
        self.btn_sha512 = QtGui.QRadioButton(self.centralwidget)
        self.btn_sha512.setObjectName(_fromUtf8("btn_sha512"))
        self.buttonGroup.addButton(self.btn_sha512)
        self.gridLayout.addWidget(self.btn_sha512, 21, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 24, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 26, 0, 1, 1)
        self.btn_sha256 = QtGui.QRadioButton(self.centralwidget)
        self.btn_sha256.setObjectName(_fromUtf8("btn_sha256"))
        self.buttonGroup.addButton(self.btn_sha256)
        self.gridLayout.addWidget(self.btn_sha256, 20, 1, 1, 1)
        self.hfsDiskBtn = QtGui.QCheckBox(self.centralwidget)
        self.hfsDiskBtn.setObjectName(_fromUtf8("hfsDiskBtn"))
        self.gridLayout.addWidget(self.hfsDiskBtn, 7, 0, 1, 2)
        self.sfWarningsBtn = QtGui.QCheckBox(self.centralwidget)
        self.sfWarningsBtn.setChecked(True)
        self.sfWarningsBtn.setObjectName(_fromUtf8("sfWarningsBtn"))
        self.gridLayout.addWidget(self.sfWarningsBtn, 15, 1, 1, 1)
        self.throttleSiegfriedBtn = QtGui.QCheckBox(self.centralwidget)
        self.throttleSiegfriedBtn.setObjectName(_fromUtf8("throttleSiegfriedBtn"))
        self.gridLayout.addWidget(self.throttleSiegfriedBtn, 17, 0, 1, 1)
        self.bulkExtractorBtn = QtGui.QCheckBox(self.centralwidget)
        self.bulkExtractorBtn.setObjectName(_fromUtf8("bulkExtractorBtn"))
        self.gridLayout.addWidget(self.bulkExtractorBtn, 15, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Brunnhilde GUI", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Checksum algorithm</span></p></body></html>", None))
        self.diskImageBrowseBtn.setText(_translate("MainWindow", "Browse", None))
        self.diskImageSource.setPlaceholderText(_translate("MainWindow", "/path/to/disk/image", None))
        self.destination.setPlaceholderText(_translate("MainWindow", "/path/to/reports/directory", None))
        self.startScanBtn.setText(_translate("MainWindow", "Start scan", None))
        self.directorySource.setPlaceholderText(_translate("MainWindow", "/path/to/directory", None))
        self.destinationBrowseBtn.setText(_translate("MainWindow", "Browse", None))
        self.radioButton_2.setText(_translate("MainWindow", "Disk image", None))
        self.directoryBrowseBtn.setText(_translate("MainWindow", "Browse", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Choose source</span></p></body></html>", None))
        self.identifier.setPlaceholderText(_translate("MainWindow", "Enter accession no. or other identifer (no spaces)", None))
        self.radioButton.setText(_translate("MainWindow", "Directory", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Destination for reports</span></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Options</span></p></body></html>", None))
        self.scanArchivesBtn.setText(_translate("MainWindow", "Scan archive files (zip, tar, etc.)", None))
        self.removeFilesBtn.setText(_translate("MainWindow", "Remove files carved from disk image at end of process", None))
        self.btn_sha1.setText(_translate("MainWindow", "sha1", None))
        self.skipClamscanBtn.setText(_translate("MainWindow", "Skip virus scan", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Accession number or identifier</span></p></body></html>", None))
        self.btn_md5.setText(_translate("MainWindow", "md5", None))
        self.btn_sha512.setText(_translate("MainWindow", "sha512", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Output (stdout)</span></p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Errors (stderr)</span></p></body></html>", None))
        self.btn_sha256.setText(_translate("MainWindow", "sha256", None))
        self.hfsDiskBtn.setText(_translate("MainWindow", "Hierarchical File System (HFS)-formatted disk", None))
        self.sfWarningsBtn.setText(_translate("MainWindow", "Include Siegfried warnings in HTML", None))
        self.throttleSiegfriedBtn.setText(_translate("MainWindow", "Throttle Siegfried", None))
        self.bulkExtractorBtn.setText(_translate("MainWindow", "Run bulk_extractor", None))

