#!/bin/bash

python3 -m pip install pyqt5

install_dir='/usr/share/brunnhilde-gui'

if [ -d $install_dir ]; then
  sudo rm -rf $install_dir
fi

sudo mkdir $install_dir

sudo mv design.py $install_dir
sudo mv design.ui $install_dir
sudo mv icon.png $install_dir
sudo mv launch $install_dir
sudo mv main.py $install_dir

desktop_file='/home/bcadmin/Desktop/Forensics and Reporting/Brunnhilde GUI.desktop'

sudo touch $desktop_file
echo '[Desktop Entry]' | sudo tee --append $desktop_file
echo 'Type=Application' | sudo tee --append $desktop_file
echo 'Name=Brunnhilde GUI' | sudo tee --append $desktop_file
echo 'Exec=/usr/share/brunnhilde-gui/launch' | sudo tee --append $desktop_file
echo 'Icon=/usr/share/brunnhilde-gui/icon.png' | sudo tee --append $desktop_file

sudo chown bcadmin:bcadmin $desktop_file
sudo chmod 644 $desktop_file
sudo chown -R bcadmin:bcadmin $install_dir

sudo chmod u+x $desktop_file
sudo chmod u+x $install_dir/launch
